DELETE
FROM CUSTOMER;

INSERT INTO CUSTOMER(NAME)
VALUES ('JACOB');
INSERT INTO CUSTOMER(NAME)
VALUES ('JEREMY');
INSERT INTO CUSTOMER(NAME)
VALUES ('JOHNSON');


DELETE
FROM USERS;

INSERT INTO USERS(NAME)
VALUES ('ALICE');
INSERT INTO USERS(NAME)
VALUES ('BOB');
INSERT INTO USERS(NAME)
VALUES ('CAROLINE');

DELETE
FROM GROUPS;

INSERT INTO GROUPS(NAME)
VALUES ('IT');
INSERT INTO GROUPS(NAME)
VALUES ('TECH');
INSERT INTO GROUPS(NAME)
VALUES ('BUSINESS');