CREATE TABLE IF NOT EXISTS CUSTOMER(
    ID SERIAL PRIMARY KEY,
    NAME TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS USERS(
    ID SERIAL PRIMARY KEY,
    NAME TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS GROUPS(
    ID SERIAL PRIMARY KEY,
    NAME TEXT NOT NULL
);

